name: Login AWS
description: "Login to AWS and configure credentials"

inputs:
  role-to-assume:
    description: "Assumed role used in workflow (ignored if workflow is executed in local)"
    required: true
  aws-access-key-id:
    description: "AWS access key ID (for local debug only)"
    required: false
    default: ""
  aws-secret-access-key:
    description: "AWS secret access key (for local debug only)"
    required: false
    default: ""
  aws-session-token:
    description: "AWS session token (for local debug only)"
    required: false
    default: ""
  aws-region:
    description: "AWS region"
    required: false
    default: "ap-northeast-1"
  apt-cache-valid-seconds:
    description: "Update the apt cache if it's older than this in seconds (for local debug only)"
    required: false
    default: 604800  # 60 * 60 * 24 * 7

runs:
  using: "composite"
  steps:
    # GitHub Action上ではインストールされているawscliとlessがActだと無い
    - name: Install commands for local exec
      if: ${{ env.ACT }}
      shell: bash
      env:
        CACHE_VALID_SECONDS: ${{ inputs.apt-cache-valid-seconds }}
      run: |
        # update the apt cache if it's older than the cache-valid-seconds
        APT_LISTS_PATH="/var/lib/apt/lists"
        APT_UPDATE_SUCCESS_STAMP_PATH="/var/lib/apt/periodic/update-success-stamp"
        if [ -e "${APT_UPDATE_SUCCESS_STAMP_PATH}" ]; then
          CACHE_TIME=$(stat -c %Y "${APT_UPDATE_SUCCESS_STAMP_PATH}")
        elif [ -e "${APT_LISTS_PATH}" ] && [ -n "$(ls -A ${APT_LISTS_PATH})" ] ; then
          CACHE_TIME=$(stat -c %Y "${APT_LISTS_PATH}")
        else
          CACHE_TIME=0
        fi
        if [ $(( "${CACHE_TIME}" + "${CACHE_VALID_SECONDS}" )) -lt $(date +%s) ]; then
          apt-get update
        fi

        # install less
        which less || apt-get install -y less

        # install awscli
        if ! which aws; then
          curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
          unzip awscliv2.zip
          sudo ./aws/install
        fi

    - name: Configure AWS credentials
      if: ${{ !env.ACT }}
      uses: aws-actions/configure-aws-credentials@v4
      with:
        role-to-assume: ${{ inputs.role-to-assume }}
        aws-region: ${{ inputs.aws-region }}

    - name: Configure AWS credentials for local exec
      if: ${{ env.ACT }}
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ inputs.aws-access-key-id }}
        aws-secret-access-key: ${{ inputs.aws-secret-access-key }}
        aws-session-token: ${{ inputs.aws-session-token }}
        aws-region: ${{ inputs.aws-region }}
        role-to-assume: null  # act seems propagate inputs to actions called in an action

    # ebコマンドを実行するためには、クレデンシャルがファイルとして存在していることが必要
    - name: Create credentials file
      shell: bash
      run: |
        # 機微情報は"configure-aws-credentials"アクションによって環境変数に格納されている
        aws configure set aws_access_key_id $AWS_ACCESS_KEY_ID
        aws configure set aws_secret_access_key $AWS_SECRET_ACCESS_KEY
        aws configure set aws_session_token $AWS_SESSION_TOKEN
        aws configure set region $AWS_REGION
