name: Login AWS
description: "Login to AWS and configure credentials"

inputs:
  role-to-assume:
    description: "Assumed role used in workflow (ignored if workflow is executed in local)"
    required: true
  aws-access-key-id:
    description: "AWS access key ID (for local debug only)"
    required: false
    default: ""
  aws-secret-access-key:
    description: "AWS secret access key (for local debug only)"
    required: false
    default: ""
  aws-session-token:
    description: "AWS session token (for local debug only)"
    required: false
    default: ""
  aws-region:
    description: "AWS region"
    required: false
    default: "ap-northeast-1"

runs:
  using: "composite"
  steps:
    # GitHub Action上ではインストールされているawscliとlessがActだと無い
    - name: Install commands for local exec
      if: ${{ env.ACT }}
      shell: bash
      run: |
        sudo apt update && apt install -y less

        curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
        unzip awscliv2.zip
        sudo ./aws/install

    - name: Configure AWS credentials
      if: ${{ !env.ACT }}
      uses: aws-actions/configure-aws-credentials@v1
      with:
        role-to-assume: ${{ inputs.role-to-assume }}
        aws-region: ${{ inputs.aws-region }}

    - name: Configure AWS credentials for local exec
      if: ${{ env.ACT }}
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ inputs.aws-access-key-id }}
        aws-secret-access-key: ${{ inputs.aws-secret-access-key }}
        aws-session-token: ${{ inputs.aws-session-token }}
        aws-region: ${{ inputs.aws-region }}

    # ebコマンドを実行するためには、クレデンシャルがファイルとして存在していることが必要
    - name: Create credentials file
      shell: bash
      run: |
        # 機微情報は"configure-aws-credentials"アクションによって環境変数に格納されている
        aws configure set aws_access_key_id $AWS_ACCESS_KEY_ID
        aws configure set aws_secret_access_key $AWS_SECRET_ACCESS_KEY
        aws configure set aws_session_token $AWS_SESSION_TOKEN
        aws configure set region $AWS_REGION
