name: Install deploy tools
description: "Install tools for deployment"

inputs:
  python-version:
    description: "Version of installed python"
    required: false
    default: '3.10'

runs:
  using: "composite"
  steps:
    - name: Set up python
      uses: actions/setup-python@v4
      with:
        python-version: ${{ inputs.python-version }}

    - name: Install ebi and awsebcli
      shell: bash
      run: |
        # Tentative solution for Cython version-related problems
        # See: https://github.com/yaml/pyyaml/issues/601
        pip install wheel
        pip install "Cython<3.0" "pyyaml==5.4.1" --no-build-isolation
        pip install -q -U ebi 'boto3<1.21' 'awsebcli==3.20.3'

        # Check commands
        eb --version
        ebi --help

    - name: Install yq
      shell: bash
      working-directory: /tmp
      run: |
        wget -q https://github.com/mikefarah/yq/releases/download/v4.34.2/yq_linux_amd64.tar.gz -O - | tar xz
        sudo mv yq_linux_amd64 /usr/local/bin/yq

        # Check command
        yq -V
