name: Install deploy tools
description: "Install tools for deployment"

inputs:
  python-version:
    description: "Version of installed python"
    required: false
    default: "3.12"

runs:
  using: "composite"
  steps:
    - name: Set up python
      uses: actions/setup-python@a309ff8b426b58ec0e2a45f0f869d46889d02405 # v6.2.0
      with:
        python-version: ${{ inputs.python-version }}

    - name: Set up uv
      uses: astral-sh/setup-uv@08807647e7069bb48b6ef5acd8ec9567f424441b # v8.1.0

    - name: Install ebi and awsebcli
      shell: bash
      env:
        REQUIREMENTS_FILE: ${{ github.action_path }}/requirements.txt
      run: |
        uv pip install -q --system --require-hashes -r "$REQUIREMENTS_FILE"

        # Check commands
        eb --version
        ebi --help

    - name: Install yq
      shell: bash
      working-directory: /tmp
      run: |
        wget -q https://github.com/mikefarah/yq/releases/download/v4.53.2/yq_linux_amd64.tar.gz -O - | tar xz
        sudo mv yq_linux_amd64 /usr/local/bin/yq

        # Check command
        yq -V
