name: Build image
description: "Build Docker image"

inputs:
  repository-name:
    description: "The name of repository used to image tag"
    required: false
    default: ${{ github.event.repository.name }}
  use-image-cache:
    description: Flag to enable caching docker image
    required: false
    default: "true"
  build-context:
    description: The information of build context. Only git context and path context are acceptable.
    required: false
    default: "."
  build-args:
    description: List of build-time variables
    required: false
    default: ""
  platforms:
    description: List or comma separated values of cpu architecture platform.
    required: false
    default: ""
  file:
    description: Path to the Dockerfile
    required: false
    default: ""

outputs:
  image-name:
    description: "The Docker image name used to build"
    value: local/${{ inputs.repository-name }}

runs:
  using: "composite"
  steps:
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Cache Docker layers
      uses: actions/cache@v3
      if: ${{ inputs.use-image-cache == 'true' }}
      with:
        path: /tmp/.buildx-cache
        key: ${{ runner.os }}-buildx-${{ github.sha }}
        restore-keys: |
          ${{ runner.os }}-buildx-

    - name: Build Docker image
      uses: docker/build-push-action@v3
      with:
        context: ${{ inputs.build-context }}
        build-args: ${{ inputs.build-args }}
        load: true # Buildだけ行いイメージデータをエクスポートする
        tags: local/${{ inputs.repository-name }}
        platforms: ${{ inputs.platforms }}
        cache-from: type=local,src=/tmp/.buildx-cache
        cache-to: type=local,dest=/tmp/.buildx-cache-new,mode=max
        file: ${{ inputs.file }}

    - name: Move cache
      shell: bash
      run: |
        rm -rf /tmp/.buildx-cache
        mv /tmp/.buildx-cache-new /tmp/.buildx-cache
